"""Scan canonical predictions and emit a model x task coverage matrix.

Outputs:
  output/coverage_matrix.csv  (wide: rows=models, cols=tasks, cells=sources or empty)
  docs/coverage_matrix.md     (human-readable, with per-model missing lists)

Run after any benchmark rerun:
    python3 code/build_coverage_matrix.py
"""
import csv
import argparse
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def _repo_path(path: Path | str | None) -> Path | None:
    if path is None:
        return None
    path = Path(path)
    if path.is_absolute():
        return path
    return REPO_ROOT / path


def list_tasks(tasks_dirs: list[Path] | None = None) -> list[str]:
    tasks_dirs = tasks_dirs or [REPO_ROOT / "tasks"]
    tasks: set[str] = set()
    for tasks_dir in tasks_dirs:
        tasks.update(p.stem for p in tasks_dir.glob("*.yaml"))
    return sorted(tasks)


def list_models(models_dir: Path | None = None) -> list[tuple[str, str]]:
    models_dir = models_dir or REPO_ROOT / "models"
    out: list[tuple[str, str]] = []
    for p in sorted(models_dir.glob("*.yaml")):
        spec = yaml.safe_load(p.read_text()) or {}
        name = spec.get("name")
        if name:
            out.append((p.stem, str(name)))
    return out


def find_predictions_files(canonical_path: Path | None = None,
                           archive_root: Path | None = None,
                           sidecar_root: Path | None = None,
                           include_sidecars: bool = False,
                           ) -> list[tuple[str, Path]]:
    canonical_path = canonical_path or REPO_ROOT / "output" / "predictions.csv"
    archive_root = archive_root or REPO_ROOT / "output" / "archive"
    sidecar_root = sidecar_root or REPO_ROOT / "output" / "sidecar"
    files: list[tuple[str, Path]] = []
    if canonical_path.exists():
        files.append(("canonical", canonical_path))
    if include_sidecars and sidecar_root.exists():
        for fn in sorted(sidecar_root.iterdir()):
            if fn.suffix.lower() != ".csv":
                continue
            if "prediction" not in fn.name.lower():
                continue
            label = f"live_sidecar_{fn.stem.removesuffix('_predictions')}"
            files.append((label, fn))
    if include_sidecars and archive_root.exists():
        for sidecar_dir in sorted(archive_root.iterdir()):
            if not sidecar_dir.is_dir():
                continue
            for fn in sorted(sidecar_dir.iterdir()):
                if fn.suffix.lower() != ".csv":
                    continue
                if "prediction" not in fn.name.lower():
                    continue
                files.append((sidecar_dir.name, fn))
    return files


def scan_predictions(files: list[tuple[str, Path]]
                     ) -> dict[tuple[str, str], set[str]]:
    cells: dict[tuple[str, str], set[str]] = defaultdict(set)
    for label, path in files:
        with path.open(newline="") as f:
            reader = csv.DictReader(f)
            if not reader.fieldnames:
                continue
            if "task" not in reader.fieldnames or "model" not in reader.fieldnames:
                continue
            for row in reader:
                cells[(row["task"], row["model"])].add(label)
    return cells


def build_matrix_rows(tasks: list[str],
                      models: list[tuple[str, str]],
                      cells: dict[tuple[str, str], set[str]]
                      ) -> tuple[list[str], list[list[str]]]:
    headers = ["model"] + tasks
    rows: list[list[str]] = []
    extra_models = sorted({m for (_, m) in cells} - {n for (_, n) in models})
    ordered = [n for (_, n) in models] + extra_models
    for name in ordered:
        row = [name]
        for t in tasks:
            srcs = cells.get((t, name), set())
            row.append(",".join(sorted(srcs)) if srcs else "")
        rows.append(row)
    return headers, rows


def write_csv(path: Path, headers: list[str], rows: list[list[str]]) -> None:
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(headers)
        w.writerows(rows)


def write_markdown(out_path: Path,
                   tasks: list[str],
                   models: list[tuple[str, str]],
                   cells: dict[tuple[str, str], set[str]],
                   files: list[tuple[str, Path]],
                   task_sources: list[Path] | None = None,
                   title: str = "Benchmark coverage matrix") -> None:
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("Auto-generated by `python3 code/build_coverage_matrix.py`. Do not edit by hand.")
    lines.append("")
    extra_models = sorted({m for (_, m) in cells} - {n for (_, n) in models})
    ordered = [n for (_, n) in models] + extra_models
    n_cells = len(tasks) * len(ordered)
    n_filled = sum(1 for name in ordered for t in tasks if cells.get((t, name)))
    task_sources = task_sources or [REPO_ROOT / "tasks"]
    rel_sources = ", ".join(
        f"`{src.relative_to(REPO_ROOT)}/*.yaml`" if src.is_relative_to(REPO_ROOT) else f"`{src}/*.yaml`"
        for src in task_sources
    )
    lines.append(f"- Tasks: {len(tasks)} (from {rel_sources})")
    lines.append(f"- Models: {len(models)} (from `models/*.yaml`)")
    if extra_models:
        lines.append(f"- Models seen in predictions but not in `models/`: "
                     + ", ".join(f"`{m}`" for m in extra_models))
    lines.append(f"- Sources scanned: {len(files)} predictions files")
    pct = n_filled / n_cells if n_cells else 0
    lines.append(f"- Coverage: {n_filled} / {n_cells} cells filled ({pct:.0%})")
    lines.append("")

    lines.append("## Matrix")
    lines.append("")
    lines.append("`X` = at least one row present in some predictions file. blank = missing.")
    lines.append("")
    hdr = ["model"] + tasks
    lines.append("| " + " | ".join(hdr) + " |")
    lines.append("|" + "|".join(["---"] * len(hdr)) + "|")
    for name in ordered:
        marks = ["X" if cells.get((t, name)) else "" for t in tasks]
        lines.append("| " + " | ".join([name] + marks) + " |")
    lines.append("")

    lines.append("## Missing cells per model")
    lines.append("")
    for name in ordered:
        missing = [t for t in tasks if not cells.get((t, name))]
        if missing:
            lines.append(f"- **{name}** ({len(missing)}): {', '.join(missing)}")
        else:
            lines.append(f"- **{name}**: complete")
    lines.append("")

    lines.append("## Missing cells per task")
    lines.append("")
    for t in tasks:
        missing_models = [name for name in ordered if not cells.get((t, name))]
        if missing_models:
            lines.append(f"- **{t}** ({len(missing_models)}): "
                         + ", ".join(missing_models))
        else:
            lines.append(f"- **{t}**: complete")
    lines.append("")

    lines.append("## Sources scanned")
    lines.append("")
    for label, src in files:
        rel = src.relative_to(REPO_ROOT) if src.is_relative_to(REPO_ROOT) else src
        lines.append(f"- `{label}` -> `{rel}`")
    lines.append("")

    out_path.write_text("\n".join(lines))


def refresh(
    verbose: bool = True,
    tasks_dirs: list[Path] | None = None,
    models_dir: Path | None = None,
    canonical_path: Path | None = None,
    archive_root: Path | None = None,
    sidecar_root: Path | None = None,
    output_csv: Path | None = None,
    output_md: Path | None = None,
    include_sidecars: bool = False,
    title: str = "Benchmark coverage matrix",
) -> tuple[Path, Path]:
    tasks_dirs = [_repo_path(p) for p in tasks_dirs] if tasks_dirs else None
    models_dir = _repo_path(models_dir)
    canonical_path = _repo_path(canonical_path)
    archive_root = _repo_path(archive_root)
    sidecar_root = _repo_path(sidecar_root)
    output_csv = _repo_path(output_csv)
    output_md = _repo_path(output_md)

    tasks = list_tasks(tasks_dirs)
    models = list_models(models_dir)
    files = find_predictions_files(
        canonical_path=canonical_path,
        archive_root=archive_root,
        sidecar_root=sidecar_root,
        include_sidecars=include_sidecars,
    )
    cells = scan_predictions(files)
    headers, rows = build_matrix_rows(tasks, models, cells)
    out_csv = output_csv or REPO_ROOT / "output" / "coverage_matrix.csv"
    out_md = output_md or REPO_ROOT / "docs" / "coverage_matrix.md"
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    write_csv(out_csv, headers, rows)
    write_markdown(
        out_md,
        tasks,
        models,
        cells,
        files,
        task_sources=tasks_dirs,
        title=title,
    )
    if verbose:
        print(f"wrote {out_csv.relative_to(REPO_ROOT)}")
        print(f"wrote {out_md.relative_to(REPO_ROOT)}")
    return out_csv, out_md


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tasks-dir",
        action="append",
        type=Path,
        help="Directory of task manifests to include. Can be repeated. Defaults to tasks/.",
    )
    parser.add_argument("--models-dir", type=Path, help="Directory of model manifests.")
    parser.add_argument("--canonical-path", type=Path, help="Canonical predictions CSV.")
    parser.add_argument("--archive-root", type=Path, help="Archive root containing sidecar runs.")
    parser.add_argument("--sidecar-root", type=Path, help="Live sidecar output directory.")
    parser.add_argument(
        "--include-sidecars",
        action="store_true",
        help="Also scan live sidecar and archive prediction files.",
    )
    parser.add_argument("--output-csv", type=Path, help="Coverage matrix CSV output path.")
    parser.add_argument("--output-md", type=Path, help="Coverage matrix Markdown output path.")
    parser.add_argument("--title", default="Benchmark coverage matrix", help="Markdown title.")
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    refresh(
        tasks_dirs=args.tasks_dir,
        models_dir=args.models_dir,
        canonical_path=args.canonical_path,
        archive_root=args.archive_root,
        sidecar_root=args.sidecar_root,
        output_csv=args.output_csv,
        output_md=args.output_md,
        include_sidecars=args.include_sidecars,
        title=args.title,
    )
